---
name: lf-edge/eden Test suite

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'
  pull_request_review:
    types: [submitted]
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_pr_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl and jq
        run: apt-get update && apt-get install -y curl jq

      - name: Check Image Availability
        run: |
          DOCKER_HUB_PATH="evebuild/danger"
          # currently we only test amd64 (kvms and xen) with Eden
          IMAGE_AMD64_XEN="pr${{ github.event.pull_request.number }}-xen"
          IMAGE_AMD64_KVM="pr${{ github.event.pull_request.number }}-kvm"

          amd64_xen_res=$(curl -s "https://hub.docker.com/v2/repositories/${DOCKER_HUB_PATH}/tags/${IMAGE_AMD64_XEN}")
          amd64_kvm_res=$(curl -s "https://hub.docker.com/v2/repositories/${DOCKER_HUB_PATH}/tags/${IMAGE_AMD64_KVM}")
          if [[ "$(echo "$amd64_xen_res" | jq -r '.name')" == "${IMAGE_AMD64_XEN}" && "$(echo "$amd64_kvm_res" | jq -r '.name')" == "${IMAGE_AMD64_KVM}" ]]; then
              echo "Docker image ${DOCKER_HUB_PATH}:${IMAGE_AMD64_XEN} and ${DOCKER_HUB_PATH}:${IMAGE_AMD64_KVM} are available on Docker Hub."
              exit 0
          else
              echo "Docker image ${DOCKER_HUB_PATH}:${IMAGE_AMD64_XEN} and ${DOCKER_HUB_PATH}:${IMAGE_AMD64_KVM} are not available on Docker Hub."
              exit 1
          fi

  report_pr_publish:
    needs: check_pr_publish
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Docker image is not available on Docker Hub to run Eden PR tests. Please wait for the image to be built and published.'
            })

  test_suite_pr:
    needs: check_pr_publish
    if: github.event.review.state == 'approved'
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "evebuild/danger:pr${{ github.event.pull_request.number  }}"

  test_suite_master:
    if: github.ref == 'refs/heads/master'
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "lfedge/eve:snapshot"

  test_suite_tag:
    if: startsWith(github.ref, 'refs/tags')
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "lfedge/eve:${{ github.ref_name }}"
